#cloud-config
# vim: syntax=yaml
#
write_files:
- encoding: b64
  content: ${pg_credentials}
  owner: root:root
  path: /root/pg_credentials.json
  permissions: '0600'
- encoding: b64
  content: ${cos_credentials}
  owner: root:root
  path: /root/cos_credentials.json
  permissions: '0600'
- encoding: b64
  content: ${app_deploy}
  owner: root:root
  path: /root/app-deploy-backend.sh
  permissions: '0700'

runcmd:
 - [ bash, /root/app-deploy-backend.sh ]

# phone_home: if this dictionary is present, then the phone_home
# cloud-config module will post specified data back to the given
# url
# default: none
# phone_home:
#   url: http://my.foo.bar/$INSTANCE/
#   post: all
#   tries: 10
#
# phone_home:
#   url: http://my.example.com/$INSTANCE_ID/
#   post: [ pub_key_dsa, pub_key_rsa, pub_key_ecdsa, instance_id ]
